version: '3.7'

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: symfony_php:latest
    container_name: symfony_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - symfony

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - symfony

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: symfony_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: training_management
      MYSQL_ROOT_PASSWORD: secret_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - symfony

#Volumes
volumes:
  dbdata:
    driver: local

#Networks
networks:
  symfony:
    driver: bridge
