version: '3.7'

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: symfony_php:latest
    container_name: symfony_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - symfony

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - symfony

#Networks
networks:
  symfony:
    driver: bridge
